name: poster-stemgnn
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - ipykernel
    - pandera
    - kedro
    - dvc
    - numpy
    - scipy
    - simdkalman
    - tsmoothie
    - ipykernel
    - pandas
    - omegaconf
    - matplotlib
    - black
    - sktime
    - pandera[strategies]
    - pandera[io]
    - scikit-learn
    - joblib
    - typing-extensions
    - streamlit
    - click
    - black