name: poster-stemgnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - mlflow
  - ipykernel
  - pip:
    - numpy
    - scipy
    - pandas
    - dvc
    - pandera
    - scikit-learn
    - hydra-core
    - hydra-optuna-sweeper
    - ipykernel
    - simdkalman
    - tsmoothie
    - omegaconf
    - matplotlib
    - pandera[strategies]
    - pandera[io]
    - joblib
    - typing-extensions
    - streamlit
    - click
