defaults:
  - _self_
  - model: pyg
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # - override hydra/launcher: ray
  # - override hydra/launcher: joblib
  # - override hydra/launcher: ray
catalogue:
  raw: data/raw/sst.csv
  clean: data/clean/sst.csv
  impute: data/impute/sst.csv
  model_in: data/model_in/sst.csv
  meta: data/meta/A.csv
  scratch: data/scratch/df.mmap
  scaler: data/scaler/scaler.pkl
  output:
    summary: summary.yml

catalog: ${catalogue}
prepare:
  dt_start: ${params.dt_start}
  dt_end: ${params.dt_end}

params:
  dt_start: '2018'
  dt_end: '2021'
  n_neighbors: 3
  resampler: 12 
  pred_step: 1  


default:
  imputation: knn

mlflow:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  MLFLOW_S3_ENDPOINT_URL: 
  TRACKING_SERVER: http://localhost:23005



  

  

  






