# @package _global_
# RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE: true
# AWS_ACCESS_KEY_ID: minio
# AWS_SECRET_ACCESS_KEY: minio123
# MLFLOW_S3_ENDPOINT_URL: http://localhost:23000

log_dir: data/log/pyg

mlflow: 
  runname: "pyg_run4"
  experiment_name: "pyg_experiment"
  tracking_port: 23002

model: # define default value
  # lag_hour: 14
  hidden_size: 32  # default 32
  in_channels: 1
  dropout: 0.1

optimizer:
  lr: 0.01

params:
  num_epochs: 10
  
hydra:
  # job:
  #   env_set:
  #     # CUDA_VISIBLE_DEVICES: "1"
  #     # RANK: ${hydra:job.num}
  #     # RANK: 
  # launcher:
  #   ray:
  #     init:
  #       num_cpus: 40
  #       num_gpus: 8
  #     remote:
  #       num_cpus: 2
  #       num_gpus: 1        
  run:
    dir: ${log_dir}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

  sweeper:
    direction: minimize
    study_name: pyg
    storage: null
    n_trials: 50
    n_jobs: 1
    sampler:
      seed: 123

    search_space:
      model.hidden_size:
        type: int
        low: 2
        high: 128
        step: 1
      model.in_channels:
        type: int
        low: 1
        high: 31 # max 1 month
        step: 1
      model.dropout:
        type: float
        low: 0
        high: 0.5
        step: 0.1
      optimizer.lr:
        type: float
        low: 0.0001
        high: 0.1
        log: true
