# @package _global_

api_version: 1.1
runname: stemgnn_v${api_version}
args:
  train: True
  evaluate: True
  dataset: 'ECG_data'
  window_size: 31
  horizon: 1
  train_length: 7
  valid_length: 2
  test_length: 1
  epoch: 20
  device: cuda
  validate_freq: 1
  norm_method: 'z_score'
  optimizer: 'RMSProp'
  early_stop: False
  exponential_decay_step: 5
  lr: 0.0001
  multi_layer: 5  
  batch_size: 32  
  decay_rate: 0.5
  dropout_rate: 0.5
  leakyrelu_rate: 0.2

hydra:
  sweeper:
    direction: minimize
    study_name: stemgnn
    storage: sqlite:///example.db
    n_trials: 50
    n_jobs: 1
    sampler:
      seed: 123
  
    search_space:
      args.dropout_rate:
        type: float
        low: 0
        high: 0.5
      args.lr:
        type: categorical
        choices:
        - 0.0001
        - 0.005
        - 0.001
        - 0.01
      
      args.leakyrelu_rate:
        type: float
        low: 0.1
        high: 0.5

      args.multi_layer:
        type: int
        low: 1
        high: 5
        step: 1

      args.window_size:
        type: int
        low: 5
        high: 31
        step: 1

