defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

root: /workspace
prep:
  resample: 12H
  agg: mean
  src: ${root}/data/raw/sst.csv
  dest: ${root}/data/interim/prep.csv

pred:
  summary: /workspace/reports/summary.json

args:
  train: True
  evaluate: True
  dataset: 'ECG_data'
  window_size: 24
  horizon: 2
  train_length: 7
  valid_length: 2
  test_length: 1
  epoch: 10
  device: cuda
  validate_freq: 1
  norm_method: 'z_score'
  optimizer: 'RMSProp'
  early_stop: False
  exponential_decay_step: 5
  lr: 0.0001
  multi_layer: 5  
  batch_size: 32  
  decay_rate: 0.5
  dropout_rate: 0.5
  leakyrelu_rate: 0.2

hydra:
  sweeper:
    direction: minimize
    study_name: stemgnn
    storage: null
    n_trials: 10
    n_jobs: 1
    sampler:
      seed: 123

search_space:
  x:
    dropout_rate: float
    low: 0
    high: 0.5
    step: 0.05
  lr:
    type: categorical
    choices:
    - 0.0001
    - 0.005
    - 0.001
    - 0.01