name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
        
      strategy:
        matrix:
          os: [ubuntu-18.04]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.8
      - run: conda --version
      - run: which python
      - name: Run installation.
        run: |
         pip install -r requirements.txt
      - name: env test
        run: |
         python src/pyg/main.py
